In [1]:
import numpy as np
def compute_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
        return output
    
print(values)

NameError: name 'values' is not defined

In [4]:
big_array = np.random.randint(1,100,size=1000000)
#jupyter magic function
%timeit compute_reciprocals(big_array)

9.3 µs ± 62.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
np.random.seed(1)
arr1=np.random.randint(10,size=5)
arr2=np.random.randint(10,size=5)
print(arr1,arr2)
arr1=arr1-2
print(arr1,arr2)
arr3= arr1+arr2
print(arr3)
arr4=np.random.randint(10,size=(3,5))
print(arr4)
arr5=arr4 ** 2
print(arr5)


[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2] [0 1 7 6 9]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [13]:
x=np.array([-2,-1,0,1,2])
np.abs(x)
print(np.abs(x))

[2 1 0 1 2]


In [ ]:
np.linspace(start,stop,num)

In [15]:
theta=np.linspace(0,np.pi,3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))



[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
x=np.arrange(1,5)
print(x)
aggr=np.add.reduce(x)
print(aggr)
aggr=np.multiply.reduce(x)
print(aggr)

In [17]:
print(x)
accum=np.add.accumulate(x)

print(accum)

[-2 -1  0  1  2]
[-2 -3 -3 -2  0]


In [20]:
np.random.seed(3)
arr=np.random.rand(1000000)#rand():create 0_! nu,ners
print(arr)
print(np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
500422.19897015305


In [21]:
%timeit sum(arr)

52.2 ms ± 367 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
%timeit np.sum(arr)

567 µs ± 39.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [26]:
print(np.max(arr))
print("min=,",np.min(arr))
print("mean=",np.mean(arr))
print("median",np.median(arr))
print("percetile",np.percentile(arr,90))
print(np.any(arr>1))
print(np.all(arr>0))

0.9999996367889004
min=, 1.5496004267534502e-06
mean= 0.500422198970153
median 0.5005659265960778
percetile 0.9001765340710965
False
True


In [3]:
#다차원 집계
np.random.seed(5)
arr=np.random.randint(10,size=(3,4))
print(arr)

print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))


[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
