In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
#creating a Numpy Array
list = [1,2,3,4]

arr=np.array(list)
print(arr)

[1 2 3 4]


In [9]:

#int + object meta info 56->64
from sys import getsizeof
lst=[1,2,3,4,5,6,7]
print(getsizeof(lst))
# int 4,바이트만증가
arr=np.array(lst)
print(getsizeof(arr))

112
132


In [11]:
prices=[30,25,40,20,20,35,50,35]
new_prices=[price-5 for price in prices]
print(new_prices)

#with a ndarray
prices_arr = np.array(prices)
prices_arr = prices_arr-5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [35]:

test1=np.array([92,94,88,91,87])
test2=np.array([79,100,86,93,91])
test3=np.array([89,87,74,92,94])
test3=test3+2
test_3_fixed=test3
print(test_3_fixed)

total_grade= test1+test2+test3
print(total_grade)
final_grade=total_grade/3
print(final_grade)

jeremy_test_2=test2[3]
print(jeremy_test_2)

manual_adwoa_test1 = np.array([test1[1],test1[2]])
print(manual_adwoa_test1)

student_scores=np.array([test1,test2,test3])
print(student_scores)

print(student_scores[2,0])
print(student_scores[:,3])

a=np.array([10,2,2,4,5,3,9,8,9,7])
mask=a>5
print(mask)

selected=a[a>5]
print(selected)
#selected= a[(a>6)|(a<4)]
print(selected)

porridge=np.array([79,65,50,63,56,90,85,98,79,51])
cold=porridge[porridge<60]
hot=porridge[porridge>80]
just_righ = porridge[(porridge>60) & (porridge<80)]
print(cold)
print(hot)
print(just_righ)

[91 89 76 94 96]
[262 283 250 278 274]
[87.33333333 94.33333333 83.33333333 92.66666667 91.33333333]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 91  89  76  94  96]]
91
[91 93 94]
[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  9  8  9  7]
[50 56 51]
[90 85 98]
[79 65 63 79]
